interface = "wlx5c628b9e3d04";
http_port = 8181;
backend = {
    url = "http://localhost";
    api_key = "your-api-key-here";
    api_secret = "your-api-secret-here";
};
username = "admin";
password = "secret";
app_secret = "wlx5c628b9e3d04wlx5c628b9e3d04"