#!/bin/bash
# Tetragon Installation Script for Cyrenus Integration
# This script installs Tetragon and configures it for standalone deployment

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
TETRAGON_VERSION="v1.1.2"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/tetragon"
LOG_DIR="/var/log/tetragon"
POLICY_DIR="${CONFIG_DIR}/policies"

echo -e "${GREEN}=== Tetragon Installation for Cyrenus ===${NC}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root${NC}"
   exit 1
fi

# Check kernel version
echo -e "${YELLOW}[1/8] Checking kernel version...${NC}"
KERNEL_VERSION=$(uname -r | cut -d. -f1-2)
KERNEL_MAJOR=$(echo $KERNEL_VERSION | cut -d. -f1)
KERNEL_MINOR=$(echo $KERNEL_VERSION | cut -d. -f2)

if [[ $KERNEL_MAJOR -lt 5 ]] || [[ $KERNEL_MAJOR -eq 5 && $KERNEL_MINOR -lt 8 ]]; then
    echo -e "${RED}Error: Kernel version 5.8+ required. Current: $(uname -r)${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Kernel version $(uname -r) is compatible${NC}"

# Check required dependencies
echo -e "${YELLOW}[2/8] Checking dependencies...${NC}"
DEPS="curl jq systemctl"
for dep in $DEPS; do
    if ! command -v $dep &> /dev/null; then
        echo -e "${RED}Error: Required dependency '$dep' not found${NC}"
        exit 1
    fi
done
echo -e "${GREEN}✓ All dependencies present${NC}"

# Detect architecture
echo -e "${YELLOW}[3/8] Detecting architecture...${NC}"
ARCH=$(uname -m)
case $ARCH in
    x86_64)
        TETRAGON_ARCH="amd64"
        ;;
    aarch64)
        TETRAGON_ARCH="arm64"
        ;;
    *)
        echo -e "${RED}Error: Unsupported architecture: $ARCH${NC}"
        exit 1
        ;;
esac
echo -e "${GREEN}✓ Architecture: $ARCH (Tetragon: $TETRAGON_ARCH)${NC}"

# Download Tetragon
echo -e "${YELLOW}[4/8] Downloading Tetragon ${TETRAGON_VERSION}...${NC}"
DOWNLOAD_URL="https://github.com/cilium/tetragon/releases/download/${TETRAGON_VERSION}/tetragon-${TETRAGON_VERSION}-${TETRAGON_ARCH}.tar.gz"
TMP_DIR=$(mktemp -d)
cd $TMP_DIR

if ! curl -L -o tetragon.tar.gz "$DOWNLOAD_URL"; then
    echo -e "${RED}Error: Failed to download Tetragon${NC}"
    rm -rf $TMP_DIR
    exit 1
fi
echo -e "${GREEN}✓ Downloaded Tetragon${NC}"

# Extract and install
echo -e "${YELLOW}[5/8] Installing Tetragon binaries...${NC}"
tar -xzf tetragon.tar.gz

# Find where the binaries were extracted
echo "Searching for binaries..."
TETRAGON_BIN=$(find . -name "tetragon" -type f 2>/dev/null | head -n 1)
TETRA_BIN=$(find . -name "tetra" -type f 2>/dev/null | head -n 1)
BPF_LIB_DIR=$(find . -path "*/usr/local/lib/tetragon/bpf" -type d 2>/dev/null | head -n 1)

if [ -z "$TETRAGON_BIN" ]; then
    echo -e "${RED}Error: Could not find 'tetragon' binary in extracted archive${NC}"
    echo "Files extracted:"
    find . -maxdepth 3
    exit 1
fi

# Install binaries
echo "Installing from: $TETRAGON_BIN"
install -m 0755 "$TETRAGON_BIN" "$INSTALL_DIR/tetragon"

if [ -n "$TETRA_BIN" ]; then
    echo "Installing from: $TETRA_BIN"
    install -m 0755 "$TETRA_BIN" "$INSTALL_DIR/tetra"
else
    echo -e "${YELLOW}Warning: 'tetra' CLI binary not found${NC}"
fi

echo -e "${GREEN}✓ Installed tetragon to $INSTALL_DIR${NC}"

# Create directories
echo -e "${YELLOW}[6/8] Creating configuration and runtime directories...${NC}"
mkdir -p $CONFIG_DIR
mkdir -p $POLICY_DIR
mkdir -p $LOG_DIR
mkdir -p /var/lib/tetragon
mkdir -p /var/run/tetragon

# Install BPF lib files
if [ -n "$BPF_LIB_DIR" ]; then
    echo "Installing BPF lib files from $BPF_LIB_DIR to /var/lib/tetragon/"
    cp -r "$BPF_LIB_DIR/"* /var/lib/tetragon/
    echo -e "${GREEN}✓ Installed BPF lib files${NC}"
else
    echo -e "${RED}Error: Could not find BPF lib files in extracted archive${NC}"
    # Don't exit, maybe it comes with the binary? But likely to fail.
fi

chmod 755 $CONFIG_DIR $POLICY_DIR
chmod 755 $LOG_DIR
chmod 755 /var/lib/tetragon
chmod 755 /var/run/tetragon
echo -e "${GREEN}✓ Created directories${NC}"

# Create base configuration
echo -e "${YELLOW}[7/8] Creating Tetragon configuration...${NC}"
cat > ${CONFIG_DIR}/tetragon.yaml <<EOF
# Tetragon Configuration for Cyrenus Integration
# Generated by install_tetragon.sh

# Export configuration
export-filename: ${LOG_DIR}/tetragon.log
export-file-max-size-mb: 100
export-file-rotation-interval: 1h
export-file-max-backups: 10
export-rate-limit: 10000

# Event filtering
enable-process-cred: true
enable-process-ns: true

# Policy directory
tracing-policy-dir: ${POLICY_DIR}

# Logging
log-level: info
log-format: json

# Performance tuning
# Disable kernel features not needed for Cyrenus use case
disable-kprobe-multi: false
enable-policy-filter: true
enable-policy-filter-debug: false

# BTF (BPF Type Format) - auto-detect
btf: ""

# gRPC server (for tetra CLI)
server-address: "localhost:54321"

# Process execution monitoring
enable-process-exec: true
enable-process-exit: true

# Metrics
enable-metrics: true
metrics-server: ":9090"
EOF

echo -e "${GREEN}✓ Created configuration file${NC}"

# Create systemd service
echo -e "${YELLOW}[8/8] Creating systemd service...${NC}"
cat > /etc/systemd/system/tetragon.service <<EOF
[Unit]
Description=Tetragon eBPF Security Observability
Documentation=https://github.com/cilium/tetragon
After=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/tetragon --config-dir=${CONFIG_DIR} --procfs=/proc/
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576
LimitNPROC=1048576

# Run as root with full privileges for now to debug
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
echo -e "${GREEN}✓ Created systemd service${NC}"

# Cleanup
cd - > /dev/null
rm -rf $TMP_DIR

# Summary
echo ""
echo -e "${GREEN}=== Installation Complete ===${NC}"
echo ""
echo "Tetragon has been installed successfully!"
echo ""
echo "Next steps:"
echo "  1. Add policies to: ${POLICY_DIR}/"
echo "  2. Start Tetragon: systemctl start tetragon"
echo "  3. Enable on boot: systemctl enable tetragon"
echo "  4. Check status: systemctl status tetragon"
echo "  5. View logs: journalctl -u tetragon -f"
echo "  6. Tetragon events: tail -f ${LOG_DIR}/tetragon.log"
echo ""
echo "CLI tools:"
echo "  - tetragon: Main daemon"
echo "  - tetra: CLI for querying and managing Tetragon"
echo ""
echo -e "${YELLOW}Note: Policies must be added before starting Tetragon${NC}"
echo ""
